MODULE BR_INTRINSICS

USE, INTRINSIC :: ISO_C_BINDING
USE PARKIND1, ONLY : JPRB

IMPLICIT NONE

CONTAINS

ELEMENTAL FUNCTION BR_ATAN(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: BR_ATAN
!
INTERFACE
  PURE FUNCTION BR_ATAN_C(PIN) BIND(C,NAME="br_atan")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: BR_ATAN_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

BR_ATAN = BR_ATAN_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION


ELEMENTAL FUNCTION BR_EXP(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: BR_EXP

INTERFACE
  PURE FUNCTION BR_EXP_C(PIN) BIND(C,NAME="br_exp")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: BR_EXP_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

BR_EXP = BR_EXP_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION

ELEMENTAL FUNCTION BR_LOG(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: BR_LOG

INTERFACE
  PURE FUNCTION BR_LOG_C(PIN) BIND(C,NAME="br_log")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: BR_LOG_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

BR_LOG = BR_LOG_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION


ELEMENTAL FUNCTION BR_POW(PVAL,PPOW)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL, PPOW
REAL (KIND=JPRB)             :: BR_POW

BR_POW = BR_EXP( PPOW * BR_LOG(PVAL) )

END FUNCTION

ELEMENTAL FUNCTION BR_SIN(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: BR_SIN

INTERFACE
  PURE FUNCTION BR_SIN_C(PIN) BIND(C,NAME="br_sin")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: BR_SIN_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

BR_SIN = BR_SIN_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION BR_SIN

ELEMENTAL FUNCTION BR_ASIN(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: BR_ASIN

INTERFACE
  PURE FUNCTION BR_ASIN_C(PIN) BIND(C,NAME="br_asin")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: BR_ASIN_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

BR_ASIN = BR_ASIN_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION BR_ASIN

ELEMENTAL FUNCTION BR_COS(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: BR_COS

INTERFACE
  PURE FUNCTION BR_COS_C(PIN) BIND(C,NAME="br_cos")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: BR_COS_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

BR_COS = BR_COS_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION BR_COS

END MODULE BR_INTRINSICS
