MODULE INTRINSICS

USE, INTRINSIC :: ISO_C_BINDING
USE PARKIND1, ONLY : JPRB

IMPLICIT NONE

CONTAINS

ELEMENTAL FUNCTION ATAN(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: ATAN
!
INTERFACE
  PURE FUNCTION ATAN_C(PIN) BIND(C,NAME="br_atan")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: ATAN_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

ATAN = ATAN_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION


ELEMENTAL FUNCTION EXP(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: EXP

INTERFACE
  PURE FUNCTION EXP_C(PIN) BIND(C,NAME="br_exp")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: EXP_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

EXP = EXP_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION

ELEMENTAL FUNCTION LOG(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: LOG

INTERFACE
  PURE FUNCTION LOG_C(PIN) BIND(C,NAME="br_log")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: LOG_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

LOG = LOG_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION


ELEMENTAL FUNCTION POW(PVAL,PPOW)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL, PPOW
REAL (KIND=JPRB)             :: POW

POW = EXP( PPOW * LOG(PVAL) )

END FUNCTION

ELEMENTAL FUNCTION SIN(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: SIN

INTERFACE
  PURE FUNCTION SIN_C(PIN) BIND(C,NAME="br_sin")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: SIN_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

SIN = SIN_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION SIN

ELEMENTAL FUNCTION ASIN(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: ASIN

INTERFACE
  PURE FUNCTION ASIN_C(PIN) BIND(C,NAME="br_asin")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: ASIN_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

ASIN = ASIN_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION ASIN

ELEMENTAL FUNCTION COS(PVAL)
!$acc routine seq

REAL (KIND=JPRB), INTENT(IN) :: PVAL
REAL (KIND=JPRB)             :: COS

INTERFACE
  PURE FUNCTION COS_C(PIN) BIND(C,NAME="br_cos")
!$acc routine seq
    IMPORT C_DOUBLE
    REAL(KIND=C_DOUBLE)                  :: COS_C
    REAL(KIND=C_DOUBLE),VALUE,INTENT(IN) :: PIN
  END FUNCTION
END INTERFACE

COS = COS_C(REAL(PVAL,KIND=C_DOUBLE))

END FUNCTION COS

END MODULE INTRINSICS
