MODULE LOAD_TPHY1_MOD

USE YOMPHY1, ONLY : TPHY1

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY1
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TPHY1 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY1), INTENT (OUT) :: YD

READ (KLUN) YD%GF3
READ (KLUN) YD%GF4
READ (KLUN) YD%TREF4
READ (KLUN) YD%RCTVEG
READ (KLUN) YD%RGL
READ (KLUN) YD%SODELX
READ (KLUN) YD%GCZ0H
READ (KLUN) YD%ALBGLA
READ (KLUN) YD%ALBMAX
READ (KLUN) YD%ALBMER
READ (KLUN) YD%ALBMED
READ (KLUN) YD%ALBMIN
READ (KLUN) YD%ALCRIN
READ (KLUN) YD%ALRCN1
READ (KLUN) YD%ALRCN2
READ (KLUN) YD%EA
READ (KLUN) YD%EC2REF
READ (KLUN) YD%EMCRIN
READ (KLUN) YD%EMMGLA
READ (KLUN) YD%EMMMER
READ (KLUN) YD%EWFC
READ (KLUN) YD%EWWILT
READ (KLUN) YD%GA
READ (KLUN) YD%GC1
READ (KLUN) YD%GC1S1
READ (KLUN) YD%GC1S2
READ (KLUN) YD%GC1S3
READ (KLUN) YD%GC1S4
READ (KLUN) YD%GC1Y1
READ (KLUN) YD%GTSVAP
READ (KLUN) YD%GVEGMX
READ (KLUN) YD%GLAIMX
READ (KLUN) YD%GNEIMX
READ (KLUN) YD%GWPIMX
READ (KLUN) YD%GCGEL
READ (KLUN) YD%GC2
READ (KLUN) YD%GC2REF
READ (KLUN) YD%GC3
READ (KLUN) YD%GC31
READ (KLUN) YD%GC32
READ (KLUN) YD%GCONV
READ (KLUN) YD%GF1
READ (KLUN) YD%GWFC
READ (KLUN) YD%GWLEX
READ (KLUN) YD%GWLMX
READ (KLUN) YD%GWWILT
READ (KLUN) YD%G1B
READ (KLUN) YD%G1CGSAT
READ (KLUN) YD%G1C1SAT
READ (KLUN) YD%G1P
READ (KLUN) YD%G1WSAT
READ (KLUN) YD%G2B
READ (KLUN) YD%G2CGSAT
READ (KLUN) YD%G2C1SAT
READ (KLUN) YD%G2P
READ (KLUN) YD%G2WSAT
READ (KLUN) YD%G3CGSAT
READ (KLUN) YD%GSNC1
READ (KLUN) YD%GSNC2
READ (KLUN) YD%HSOL
READ (KLUN) YD%HSOLIWR
READ (KLUN) YD%HSOLIT0
READ (KLUN) YD%OMTPRO
READ (KLUN) YD%OMWPRO
READ (KLUN) YD%RC1MAX
READ (KLUN) YD%RCTGLA
READ (KLUN) YD%RCGMAX
READ (KLUN) YD%RD1
READ (KLUN) YD%RD2GLA
READ (KLUN) YD%RD2MER
READ (KLUN) YD%RHOMAX
READ (KLUN) YD%RHOMIN
READ (KLUN) YD%RSMAX
READ (KLUN) YD%RTINER
READ (KLUN) YD%RZ0GLA
READ (KLUN) YD%RZ0MER
READ (KLUN) YD%RZHZ0G
READ (KLUN) YD%RZHZ0M
READ (KLUN) YD%TMERGL
READ (KLUN) YD%TOEXP
READ (KLUN) YD%TOLIN
READ (KLUN) YD%WCRIN
READ (KLUN) YD%WCRINC
READ (KLUN) YD%WCRING
READ (KLUN) YD%WNEW
READ (KLUN) YD%WPMX
READ (KLUN) YD%WSMX
READ (KLUN) YD%XCRINR
READ (KLUN) YD%XCRINV
READ (KLUN) YD%LALBMERCLIM
READ (KLUN) YD%LIMC
READ (KLUN) YD%LIMW
READ (KLUN) YD%LC1VAP
READ (KLUN) YD%LCLS_HS
READ (KLUN) YD%NTVGLA
READ (KLUN) YD%NTVMER
READ (KLUN) YD%GCGELS
READ (KLUN) YD%GVEGMXS
READ (KLUN) YD%GLAIMXS
READ (KLUN) YD%GNEIMXS
READ (KLUN) YD%ALB1
READ (KLUN) YD%ALB2
READ (KLUN) YD%RLAIMX
READ (KLUN) YD%RLAI
READ (KLUN) YD%ACLS_HS
READ (KLUN) YD%NCHSP
END SUBROUTINE


END MODULE
