MODULE LOAD_TLOUIS_MOD

USE YOMLOUIS, ONLY : TLOUIS

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLOUIS
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TLOUIS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLOUIS), INTENT (OUT) :: YD

READ (KLUN) YD%RLOUIS_S0
READ (KLUN) YD%PLOUIS_S0
READ (KLUN) YD%RLOUIS_GU1
READ (KLUN) YD%RLOUIS_GU2
READ (KLUN) YD%PLOUIS_GU1
READ (KLUN) YD%PLOUIS_GU2
READ (KLUN) YD%RLOUIS_GS1
READ (KLUN) YD%RLOUIS_GS2
READ (KLUN) YD%RLOUIS_GS3
READ (KLUN) YD%RLOUIS_GS4
READ (KLUN) YD%PLOUIS_GS1
READ (KLUN) YD%PLOUIS_GS2
READ (KLUN) YD%PLOUIS_GS3
READ (KLUN) YD%PLOUIS_GS4
END SUBROUTINE


END MODULE
