MODULE LOAD_TNORGWD_MOD

USE YOMNORGWD, ONLY : TNORGWD

INTERFACE LOAD
MODULE PROCEDURE LOAD_TNORGWD
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TNORGWD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TNORGWD), INTENT (OUT) :: YD

READ (KLUN) YD%NORGWD_SCHEME
READ (KLUN) YD%NORGWD_PRMAX
READ (KLUN) YD%NORGWD_DZ
READ (KLUN) YD%NORGWD_PTROPO
READ (KLUN) YD%NORGWD_NTROPO
READ (KLUN) YD%NORGWD_RUWMAX
READ (KLUN) YD%NORGWD_SAT
READ (KLUN) YD%NORGWD_RDISS
READ (KLUN) YD%NORGWD_DELTAT
READ (KLUN) YD%NORGWD_KMIN
READ (KLUN) YD%NORGWD_KMAX
READ (KLUN) YD%NORGWD_CMIN
READ (KLUN) YD%NORGWD_CMAX
READ (KLUN) YD%NORGWD_PLAUNCH
READ (KLUN) YD%NORGWD_NLAUNCH
READ (KLUN) YD%NORGWD_PNOVERDIF
READ (KLUN) YD%NORGWD_NNOVERDIF
READ (KLUN) YD%NORGWD_DZFRON
READ (KLUN) YD%NORGWD_GFRON
READ (KLUN) YD%NORGWD_GB
END SUBROUTINE


END MODULE
