MODULE LOAD_TMSE_MOD

USE YOMMSE, ONLY : TMSE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMSE
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TMSE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMSE), INTENT (OUT) :: YD

READ (KLUN) YD%LPGDFWR
READ (KLUN) YD%LHISFWR
READ (KLUN) YD%LFTZERO
READ (KLUN) YD%NSURFEXCTLMAX
READ (KLUN) YD%NSURFEXCTL
READ (KLUN) YD%CPREFIX_SFX1
READ (KLUN) YD%CPREFIX_SFX2
READ (KLUN) YD%XZSEPS
END SUBROUTINE


END MODULE
