MODULE PREPARE_ACRANEB2_MOD

USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

PRIVATE

PUBLIC :: PREPARE_ACRANEB2

INTERFACE INTERPOLATE
  MODULE PROCEDURE INTERPOLATE2
  MODULE PROCEDURE INTERPOLATE3
END INTERFACE

CONTAINS

SUBROUTINE PREPARE_ACRANEB2( YDERDI,YDRIP,YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,KJN,KSTEP, &
!!! EXTRA ARGUMENT WRT ACRANEB2 !!!
& KGPBLK, &
! - INPUT 2D
 & PAPRS,PAPRSF,PCP,PR,PDELP,PNEB,PQ,PQCO2,PQICE,PQLI,PQO3,PT, &
! - INPUT 1D
 & PALB,PALBDIR,PEMIS,PGELAM,PGEMU,PMU0,PMU0LU,PTS,PDECRD,PCLCT, &
! - INPUT/OUTPUT
 & PGDEOSI,PGUEOSI,PGMU0,PGMU0_MIN,PGMU0_MAX, &
 & PGDEOTI,PGDEOTI2,PGUEOTI,PGUEOTI2,PGEOLT,PGEOXT, &
 & PGRPROX,PGMIXP,PGFLUXC,PGRSURF,PSDUR, &
! - OUTPUT 2D
 & PFRSO,PFRTH, &
! - OUTPUT 1D
 & PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS, &
! - INPUT 2D x 6
 & PDAER)

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM     ,JPRB

USE YOMRIP   ,ONLY : TRIP
USE YOERDI   ,ONLY : TERDI

USE LOAD_ACRANEB2_MOD

IMPLICIT NONE

! arguments
TYPE(TERDI)        :: YDERDI
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
TYPE(TRIP)         :: YDRIP
INTEGER(KIND=JPIM) :: KIDIA 
INTEGER(KIND=JPIM) :: KFDIA 
INTEGER(KIND=JPIM), INTENT(IN) :: KLON 
INTEGER(KIND=JPIM) :: KTDIA 
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM) :: KJN
INTEGER(KIND=JPIM) :: KSTEP
INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLK
REAL(KIND=JPRB) :: PAPRS(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PAPRSF(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PCP(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PR(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PDELP(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PNEB(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQ(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQCO2(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQICE(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQLI(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQO3(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PT(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PALB(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PALBDIR(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PEMIS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PGELAM(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PGEMU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PMU0(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PMU0LU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PTS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PDECRD(KLON,KGPBLK)
REAL(KIND=JPRB) :: PCLCT(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGDEOSI(KLON,0:KLEV,2,KGPBLK)
REAL(KIND=JPRB) :: PGUEOSI(KLON,0:KLEV,2,KGPBLK)
REAL(KIND=JPRB) :: PGMU0(KLON,0:0,KGPBLK) ! warning: only for NSORAYFR==1
REAL(KIND=JPRB) :: PGMU0_MIN(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGMU0_MAX(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGDEOTI(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGDEOTI2(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGUEOTI(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGUEOTI2(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGEOLT(KLON,KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGEOXT(KLON,KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGRPROX(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGMIXP(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGFLUXC(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGRSURF(KLON,KGPBLK)
REAL(KIND=JPRB) :: PSDUR(KLON,KGPBLK)
REAL(KIND=JPRB) :: PFRSO(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PFRTH(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PFRSODS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRSOPS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRSOLU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRTHDS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PDAER(KLON,KLEV,6,KGPBLK) 

! data read from datafile
CHARACTER(LEN=1024) :: CDNAME_IN
! note: non-blocked data can be read directly (e.g. derived data types)
INTEGER(KIND=JPIM) :: KLON_IN 
INTEGER(KIND=JPIM) :: KLEV_IN 

REAL(KIND=JPRB), POINTER    :: PAPRS_IN(:,:) 
REAL(KIND=JPRB), POINTER    :: PAPRSF_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PCP_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PR_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PDELP_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PNEB_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PQ_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PQCO2_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PQICE_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PQLI_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PQO3_IN(:,:) 
REAL(KIND=JPRB), POINTER    :: PT_IN(:,:)
REAL(KIND=JPRB), POINTER    :: PALB_IN(:)
REAL(KIND=JPRB), POINTER    :: PALBDIR_IN(:)
REAL(KIND=JPRB), POINTER    :: PEMIS_IN(:)
REAL(KIND=JPRB), POINTER    :: PGELAM_IN(:)
REAL(KIND=JPRB), POINTER    :: PGEMU_IN(:)
REAL(KIND=JPRB), POINTER    :: PMU0_IN(:)
REAL(KIND=JPRB), POINTER    :: PMU0LU_IN(:)
REAL(KIND=JPRB), POINTER    :: PTS_IN(:)
REAL(KIND=JPRB), POINTER    :: PDECRD_IN(:)
REAL(KIND=JPRB), POINTER    :: PCLCT_IN(:)
REAL(KIND=JPRB), POINTER :: PGDEOSI_IN(:,:,:)
REAL(KIND=JPRB), POINTER :: PGUEOSI_IN(:,:,:)
REAL(KIND=JPRB), POINTER :: PGMU0_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGMU0_MIN_IN(:)
REAL(KIND=JPRB), POINTER :: PGMU0_MAX_IN(:)
REAL(KIND=JPRB), POINTER :: PGDEOTI_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGDEOTI2_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGUEOTI_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGUEOTI2_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGEOLT_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGEOXT_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGRPROX_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGMIXP_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGFLUXC_IN(:,:)
REAL(KIND=JPRB), POINTER :: PGRSURF_IN(:)
REAL(KIND=JPRB), POINTER :: PSDUR_IN(:)
REAL(KIND=JPRB), POINTER   :: PFRSO_IN(:,:) 
REAL(KIND=JPRB), POINTER   :: PFRTH_IN(:,:) 
REAL(KIND=JPRB), POINTER   :: PFRSODS_IN(:)
REAL(KIND=JPRB), POINTER   :: PFRSOPS_IN(:)
REAL(KIND=JPRB), POINTER   :: PFRSOLU_IN(:)
REAL(KIND=JPRB), POINTER   :: PFRTHDS_IN(:)
REAL(KIND=JPRB), POINTER    :: PDAER_IN(:,:,:) 

! other local variables
INTEGER :: JLON, JBLK, JLON_IN

! load data from input file
CDNAME_IN='acraneb2.in'
CALL LOAD_ACRANEB2(CDNAME_IN, &
 & YDERDI,YDRIP,YDML_PHY_MF,KIDIA,KFDIA,KLON_IN,KTDIA,KLEV_IN,KJN,KSTEP, &
 & PAPRS_IN,PAPRSF_IN,PCP_IN,PR_IN,PDELP_IN,PNEB_IN,PQ_IN,PQCO2_IN,PQICE_IN,PQLI_IN,PQO3_IN,PT_IN, &
 & PALB_IN,PALBDIR_IN,PEMIS_IN,PGELAM_IN,PGEMU_IN,PMU0_IN,PMU0LU_IN,PTS_IN,PDECRD_IN,PCLCT_IN, &
 & PGDEOSI_IN,PGUEOSI_IN,PGMU0_IN,PGMU0_MIN_IN,PGMU0_MAX_IN, &
 & PGDEOTI_IN,PGDEOTI2_IN,PGUEOTI_IN,PGUEOTI2_IN,PGEOLT_IN,PGEOXT_IN, &
 & PGRPROX_IN,PGMIXP_IN,PGFLUXC_IN,PGRSURF_IN,PSDUR_IN, &
 & PFRSO_IN,PFRTH_IN, &
 & PFRSODS_IN,PFRSOPS_IN,PFRSOLU_IN,PFRTHDS_IN, &
 & PDAER_IN)

! set KIDIA and KFDIA manually, as they depend on user-defined KLON instead of KLON_IN
KIDIA=1
KFDIA=KLON

! check on vertical levels
IF ( KLEV /= KLEV_IN ) THEN
  CALL INTERPOLATE (0, KLEV, PAPRS_IN)
  CALL INTERPOLATE (1, KLEV, PAPRSF_IN)
  CALL INTERPOLATE (1, KLEV, PCP_IN)
  CALL INTERPOLATE (1, KLEV, PR_IN)
  CALL INTERPOLATE (1, KLEV, PDELP_IN)
  CALL INTERPOLATE (1, KLEV, PNEB_IN)
  CALL INTERPOLATE (1, KLEV, PQ_IN)
  CALL INTERPOLATE (1, KLEV, PQCO2_IN)
  CALL INTERPOLATE (1, KLEV, PQICE_IN)
  CALL INTERPOLATE (1, KLEV, PQLI_IN)
  CALL INTERPOLATE (0, KLEV, PQO3_IN)
  CALL INTERPOLATE (1, KLEV, PT_IN)
  CALL INTERPOLATE (0, KLEV, PFRSO_IN)
  CALL INTERPOLATE (0, KLEV, PFRTH_IN)
  CALL INTERPOLATE (1, KLEV, PDAER_IN)
ENDIF

! copy blocked data into arrays
DO JBLK=1,KGPBLK
  DO JLON=1,KLON
    JLON_IN=MODULO(JLON-1,KLON_IN)+1
    PAPRS(JLON,:,JBLK) = PAPRS_IN(JLON_IN,:)
    PAPRSF(JLON,:,JBLK) = PAPRSF_IN(JLON_IN,:)
    PCP(JLON,:,JBLK) = PCP_IN(JLON_IN,:)
    PR(JLON,:,JBLK) = PR_IN(JLON_IN,:)
    PDELP(JLON,:,JBLK) = PDELP_IN(JLON_IN,:)
    PNEB(JLON,:,JBLK) = PNEB_IN(JLON_IN,:)
    PQ(JLON,:,JBLK) = PQ_IN(JLON_IN,:)
    PQCO2(JLON,:,JBLK) = PQCO2_IN(JLON_IN,:)
    PQICE(JLON,:,JBLK) = PQICE_IN(JLON_IN,:)
    PQLI(JLON,:,JBLK) = PQLI_IN(JLON_IN,:)
    PQO3(JLON,:,JBLK) = PQO3_IN(JLON_IN,:)
    PT(JLON,:,JBLK) = PT_IN(JLON_IN,:)
    PALB(JLON,JBLK) = PALB_IN(JLON_IN)
    PALBDIR(JLON,JBLK) = PALBDIR_IN(JLON_IN)
    PEMIS(JLON,JBLK) = PEMIS_IN(JLON_IN)
    PGELAM(JLON,JBLK) = PGELAM_IN(JLON_IN)
    PGEMU(JLON,JBLK) = PGEMU_IN(JLON_IN)
    PMU0(JLON,JBLK) = PMU0_IN(JLON_IN)
    PMU0LU(JLON,JBLK) = PMU0LU_IN(JLON_IN)
    PTS(JLON,JBLK) = PTS_IN(JLON_IN)
    PDECRD(JLON,JBLK) = PDECRD_IN(JLON_IN)
    PCLCT(JLON,JBLK) = PCLCT_IN(JLON_IN)
    PSDUR(JLON,JBLK) = PSDUR_IN(JLON_IN)
    PFRSO(JLON,:,JBLK) = PFRSO_IN(JLON_IN,:)
    PFRTH(JLON,:,JBLK) = PFRTH_IN(JLON_IN,:)
    PFRSODS(JLON,JBLK) = PFRSODS_IN(JLON_IN)
    PFRSOPS(JLON,JBLK) = PFRSOPS_IN(JLON_IN)
    PFRSOLU(JLON,JBLK) = PFRSOLU_IN(JLON_IN)
    PFRTHDS(JLON,JBLK) = PFRTHDS_IN(JLON_IN)
    PDAER(JLON,:,:,JBLK) = PDAER_IN(JLON_IN,:,:)
  
  ENDDO
ENDDO

! free memory
IF ( ASSOCIATED(PAPRS_IN) ) DEALLOCATE(PAPRS_IN)
IF ( ASSOCIATED(PAPRSF_IN) ) DEALLOCATE(PAPRSF_IN)
IF ( ASSOCIATED(PCP_IN) ) DEALLOCATE(PCP_IN)
IF ( ASSOCIATED(PR_IN) ) DEALLOCATE(PR_IN)
IF ( ASSOCIATED(PDELP_IN) ) DEALLOCATE(PDELP_IN)
IF ( ASSOCIATED(PNEB_IN) ) DEALLOCATE(PNEB_IN)
IF ( ASSOCIATED(PQ_IN) ) DEALLOCATE(PQ_IN)
IF ( ASSOCIATED(PQCO2_IN) ) DEALLOCATE(PQCO2_IN)
IF ( ASSOCIATED(PQICE_IN) ) DEALLOCATE(PQICE_IN)
IF ( ASSOCIATED(PQLI_IN) ) DEALLOCATE(PQLI_IN)
IF ( ASSOCIATED(PQO3_IN) ) DEALLOCATE(PQO3_IN)
IF ( ASSOCIATED(PT_IN) ) DEALLOCATE(PT_IN)
IF ( ASSOCIATED(PALB_IN) ) DEALLOCATE(PALB_IN)
IF ( ASSOCIATED(PALBDIR_IN) ) DEALLOCATE(PALBDIR_IN)
IF ( ASSOCIATED(PEMIS_IN) ) DEALLOCATE(PEMIS_IN)
IF ( ASSOCIATED(PGELAM_IN) ) DEALLOCATE(PGELAM_IN)
IF ( ASSOCIATED(PGEMU_IN) ) DEALLOCATE(PGEMU_IN)
IF ( ASSOCIATED(PMU0_IN) ) DEALLOCATE(PMU0_IN)
IF ( ASSOCIATED(PMU0LU_IN) ) DEALLOCATE(PMU0LU_IN)
IF ( ASSOCIATED(PTS_IN) ) DEALLOCATE(PTS_IN)
IF ( ASSOCIATED(PDECRD_IN) ) DEALLOCATE(PDECRD_IN)
IF ( ASSOCIATED(PCLCT_IN) ) DEALLOCATE(PCLCT_IN)
IF ( ASSOCIATED(PGDEOSI_IN) ) DEALLOCATE(PGDEOSI_IN)
IF ( ASSOCIATED(PGUEOSI_IN) ) DEALLOCATE(PGUEOSI_IN)
IF ( ASSOCIATED(PGMU0_IN) ) DEALLOCATE(PGMU0_IN)
IF ( ASSOCIATED(PGMU0_MIN_IN) ) DEALLOCATE(PGMU0_MIN_IN)
IF ( ASSOCIATED(PGMU0_MAX_IN) ) DEALLOCATE(PGMU0_MAX_IN)
IF ( ASSOCIATED(PGDEOTI_IN) ) DEALLOCATE(PGDEOTI_IN)
IF ( ASSOCIATED(PGDEOTI2_IN) ) DEALLOCATE(PGDEOTI2_IN)
IF ( ASSOCIATED(PGUEOTI_IN) ) DEALLOCATE(PGUEOTI_IN)
IF ( ASSOCIATED(PGUEOTI2_IN) ) DEALLOCATE(PGUEOTI2_IN)
IF ( ASSOCIATED(PGEOLT_IN) ) DEALLOCATE(PGEOLT_IN)
IF ( ASSOCIATED(PGEOXT_IN) ) DEALLOCATE(PGEOXT_IN)
IF ( ASSOCIATED(PGRPROX_IN) ) DEALLOCATE(PGRPROX_IN)
IF ( ASSOCIATED(PGMIXP_IN) ) DEALLOCATE(PGMIXP_IN)
IF ( ASSOCIATED(PGFLUXC_IN) ) DEALLOCATE(PGFLUXC_IN)
IF ( ASSOCIATED(PGRSURF_IN) ) DEALLOCATE(PGRSURF_IN)
IF ( ASSOCIATED(PSDUR_IN) ) DEALLOCATE(PSDUR_IN)
IF ( ASSOCIATED(PFRSO_IN) ) DEALLOCATE(PFRSO_IN)
IF ( ASSOCIATED(PFRTH_IN) ) DEALLOCATE(PFRTH_IN)
IF ( ASSOCIATED(PFRSODS_IN) ) DEALLOCATE(PFRSODS_IN)
IF ( ASSOCIATED(PFRSOPS_IN) ) DEALLOCATE(PFRSOPS_IN)
IF ( ASSOCIATED(PFRSOLU_IN) ) DEALLOCATE(PFRSOLU_IN)
IF ( ASSOCIATED(PFRTHDS_IN) ) DEALLOCATE(PFRTHDS_IN)
IF ( ASSOCIATED(PDAER_IN) ) DEALLOCATE(PDAER_IN)

END SUBROUTINE PREPARE_ACRANEB2

SUBROUTINE INTERPOLATE2 (KLEV1, KLEV2, P)

INTEGER (KIND=JPIM) :: KLEV1, KLEV2
REAL (KIND=JPRB), POINTER :: P (:,:)
REAL (KIND=JPRB) :: Z (LBOUND (P,1):UBOUND (P,1), &
                     & LBOUND (P,2):UBOUND (P,2))

Z = P

DEALLOCATE (P)

ALLOCATE (P (LBOUND (Z,1):UBOUND (Z,1), KLEV1:KLEV2))

CALL INTERPOLATE_ (Z, P)

END SUBROUTINE

SUBROUTINE INTERPOLATE3 (KLEV1, KLEV2, P)

INTEGER (KIND=JPIM) :: KLEV1, KLEV2
REAL (KIND=JPRB), POINTER :: P (:,:,:)
REAL (KIND=JPRB) :: Z (LBOUND (P,1):UBOUND (P,1), &
                     & LBOUND (P,2):UBOUND (P,2), &
                     & LBOUND (P,3):UBOUND (P,3))

INTEGER (KIND=JPIM) :: J

Z = P

DEALLOCATE (P)

ALLOCATE (P (LBOUND (Z,1):UBOUND (Z,1), KLEV1:KLEV2, LBOUND (Z,3):UBOUND (Z,3)))

DO J = LBOUND (P, 3), UBOUND (P, 3)
  CALL INTERPOLATE_ (Z (:,:,J), P (:,:,J))
ENDDO

END SUBROUTINE

SUBROUTINE INTERPOLATE_ (P1, P2)

REAL (KIND=JPRB) :: P1 (:,:), P2 (:,:)
INTEGER (KIND=JPIM) :: ILEV1A, ILEV1B, ILEV2, NLEV1, NLEV2
REAL (KIND=JPRB) :: ZWA, ZWB, ZLEV1, ZLEV2

NLEV1 = SIZE (P1, 2)
NLEV2 = SIZE (P2, 2)

DO ILEV2 = 1, NLEV2
  ZLEV2 = REAL (ILEV2 - 1, JPRB) / REAL (NLEV2 -1, JPRB) 
  ZLEV1 = 1. + ZLEV2 * REAL (NLEV1 - 1, JPRB)
  ILEV1B = MIN (CEILING (ZLEV1), NLEV1)
  ILEV1A = MAX (FLOOR   (ZLEV1),     1)  

  IF (ILEV1A == ILEV1B) THEN
    ZWA = 1.
    ZWB = 0.
  ELSE
    ZWA = REAL (ILEV1B, JPRB) - ZLEV1
    ZWB = ZLEV1 - REAL (ILEV1A, JPRB)
  ENDIF

  P2 (:, ILEV2) = ZWA * P1 (:, ILEV1A) + ZWB * P1 (:, ILEV1B)  
ENDDO

END SUBROUTINE

END MODULE PREPARE_ACRANEB2_MOD
