MODULE WRAPPER_MOD

USE PARKIND1

IMPLICIT NONE

INTERFACE WR
  MODULE PROCEDURE WR1, WR2, WR3
END INTERFACE

INTERFACE CPRS
  MODULE PROCEDURE CPRS1, CPRS2, CPRS3
END INTERFACE

CONTAINS

SUBROUTINE WRAPPER(KLON,KLEV,KGPBLK,KCOUNT,LCHECK,LSAVE)

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM     ,JPRB

USE YOMRIP   ,ONLY : TRIP
USE YOERDI   ,ONLY : TERDI

USE PREPARE_ACRANEB2_MOD
USE CHECK_ACRANEB2_MOD

use omp_lib

IMPLICIT NONE

! arguments
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLK
INTEGER(KIND=JPIM), INTENT(IN) :: KCOUNT
LOGICAL, INTENT(IN) :: LCHECK, LSAVE

#include "acraneb2.intfb.h"

! acraneb arguments
TYPE(TERDI)        :: YDERDI
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
TYPE(TRIP)         :: YDRIP
INTEGER(KIND=JPIM) :: KIDIA 
INTEGER(KIND=JPIM) :: KFDIA 
INTEGER(KIND=JPIM) :: KTDIA 
INTEGER(KIND=JPIM) :: KJN
INTEGER(KIND=JPIM) :: KSTEP
REAL(KIND=JPRB) :: PAPRS(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PAPRSF(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PCP(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PR(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PDELP(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PNEB(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQ(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQCO2(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQICE(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQLI(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQO3(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PT(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PALB(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PALBDIR(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PEMIS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PGELAM(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PGEMU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PMU0(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PMU0LU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PTS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PDECRD(KLON,KGPBLK)
REAL(KIND=JPRB) :: PCLCT(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGDEOSI(KLON,0:KLEV,2,KGPBLK)
REAL(KIND=JPRB) :: PGUEOSI(KLON,0:KLEV,2,KGPBLK)
REAL(KIND=JPRB) :: PGMU0(KLON,0:0,KGPBLK)
REAL(KIND=JPRB) :: PGMU0_MIN(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGMU0_MAX(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGDEOTI(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGDEOTI2(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGUEOTI(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGUEOTI2(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGEOLT(KLON,KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGEOXT(KLON,KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGRPROX(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGMIXP(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGFLUXC(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGRSURF(KLON,KGPBLK)
REAL(KIND=JPRB) :: PSDUR(KLON,KGPBLK)
REAL(KIND=JPRB) :: PFRSO(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PFRTH(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PFRSODS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRSOPS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRSOLU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRTHDS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PDAER(KLON,KLEV,6,KGPBLK) 

REAL(KIND=JPRB) :: PAPRS_(KLON*KGPBLK,0:KLEV) 
REAL(KIND=JPRB) :: PAPRSF_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PCP_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PR_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PDELP_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PNEB_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PQ_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PQCO2_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PQICE_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PQLI_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PQO3_(KLON*KGPBLK,0:KLEV) 
REAL(KIND=JPRB) :: PT_(KLON*KGPBLK,KLEV) 
REAL(KIND=JPRB) :: PALB_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PALBDIR_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PEMIS_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PGELAM_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PGEMU_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PMU0_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PMU0LU_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PTS_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PDECRD_(KLON*KGPBLK)
REAL(KIND=JPRB) :: PCLCT_(KLON*KGPBLK)
REAL(KIND=JPRB) :: PGDEOSI_(KLON*KGPBLK,0:KLEV,2)
REAL(KIND=JPRB) :: PGUEOSI_(KLON*KGPBLK,0:KLEV,2)
REAL(KIND=JPRB) :: PGMU0_(KLON*KGPBLK,0:0)
REAL(KIND=JPRB) :: PGMU0_MIN_(KLON*KGPBLK)
REAL(KIND=JPRB) :: PGMU0_MAX_(KLON*KGPBLK)
REAL(KIND=JPRB) :: PGDEOTI_(KLON*KGPBLK,0:KLEV)
REAL(KIND=JPRB) :: PGDEOTI2_(KLON*KGPBLK,0:KLEV)
REAL(KIND=JPRB) :: PGUEOTI_(KLON*KGPBLK,0:KLEV)
REAL(KIND=JPRB) :: PGUEOTI2_(KLON*KGPBLK,0:KLEV)
REAL(KIND=JPRB) :: PGEOLT_(KLON*KGPBLK,KLEV)
REAL(KIND=JPRB) :: PGEOXT_(KLON*KGPBLK,KLEV)
REAL(KIND=JPRB) :: PGRPROX_(KLON*KGPBLK,0:KLEV)
REAL(KIND=JPRB) :: PGMIXP_(KLON*KGPBLK,0:KLEV)
REAL(KIND=JPRB) :: PGFLUXC_(KLON*KGPBLK,0:KLEV)
REAL(KIND=JPRB) :: PGRSURF_(KLON*KGPBLK)
REAL(KIND=JPRB) :: PSDUR_(KLON*KGPBLK)
REAL(KIND=JPRB) :: PFRSO_(KLON*KGPBLK,0:KLEV) 
REAL(KIND=JPRB) :: PFRTH_(KLON*KGPBLK,0:KLEV) 
REAL(KIND=JPRB) :: PFRSODS_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PFRSOPS_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PFRSOLU_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PFRTHDS_(KLON*KGPBLK) 
REAL(KIND=JPRB) :: PDAER_(KLON*KGPBLK,KLEV,6) 

real(kind=8) :: ts,te
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD

INTEGER :: JCOUNT, JBLK, JLON


CALL PREPARE_ACRANEB2(YDERDI,YDRIP,YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,KJN,KSTEP, &
 & KGPBLK, &
 & PAPRS,PAPRSF,PCP,PR,PDELP,PNEB,PQ,PQCO2,PQICE,PQLI,PQO3,PT, &
 & PALB,PALBDIR,PEMIS,PGELAM,PGEMU,PMU0,PMU0LU,PTS,PDECRD,PCLCT, &
 & PGDEOSI,PGUEOSI,PGMU0,PGMU0_MIN,PGMU0_MAX, &
 & PGDEOTI,PGDEOTI2,PGUEOTI,PGUEOTI2,PGEOLT,PGEOXT, &
 & PGRPROX,PGMIXP,PGFLUXC,PGRSURF,PSDUR, &
 & PFRSO,PFRTH, &
 & PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS, &
 & PDAER)

ZTD = 0.
ZTC = 0.

DO JCOUNT=1,KCOUNT

    TSD = OMP_GET_WTIME ()

!$acc data &
!$acc   copyin  (YDERDI,YDRIP,YDML_PHY_MF), &
!$acc   create (PAPRS_, PAPRSF_, PCP_, PR_, PDELP_, PNEB_, PQ_, PQCO2_, PQICE_, PQLI_, PQO3_,  &
!$acc           PT_, PALB_, PALBDIR_, PEMIS_, PGELAM_, PGEMU_, PMU0_, PMU0LU_, PTS_, PDECRD_, &
!$acc           PCLCT_, PGDEOSI_, PGUEOSI_, PGMU0_, PGMU0_MIN_, PGMU0_MAX_, PGDEOTI_, PGDEOTI2_, PGUEOTI_,  &
!$acc           PGUEOTI2_, PGEOLT_, PGEOXT_, PGRPROX_, PGMIXP_, PGFLUXC_, PGRSURF_, PSDUR_, PFRSO_, &
!$acc           PFRTH_, PFRSODS_, PFRSOPS_, PFRSOLU_, PFRTHDS_, PDAER_)

#define cpi(x) CALL CPRS (x, x##_, .TRUE.)

cpi (PAPRS); cpi (PAPRSF); cpi (PCP); cpi (PR); cpi (PDELP); 
cpi (PNEB); cpi (PQ); cpi (PQCO2); cpi (PQICE); cpi (PQLI); 
cpi (PQO3); cpi (PT); cpi (PALB); cpi (PALBDIR); cpi (PEMIS); 
cpi (PGELAM); cpi (PGEMU); cpi (PMU0); cpi (PMU0LU); 
cpi (PTS); cpi (PDECRD); cpi (PCLCT); cpi (PDAER); 
cpi (PGDEOSI); cpi (PGUEOSI); cpi (PGMU0); cpi (PGMU0_MIN); 
cpi (PGMU0_MAX); cpi (PGDEOTI); cpi (PGDEOTI2);
cpi (PGUEOTI); cpi (PGUEOTI2); cpi (PGEOLT); cpi (PGEOXT); 
cpi (PGRPROX); cpi (PGMIXP); cpi (PGFLUXC); cpi (PGRSURF); 
cpi (PSDUR);

#undef cpi

    TSC = OMP_GET_WTIME ()

  CALL ACRANEB2( &
   & YDERDI,YDRIP,YDML_PHY_MF,1,KLON*KGPBLK,1_JPIM,KLON*KGPBLK,KTDIA,KLEV,KJN,KSTEP, &
  ! - INPUT 2D
   & PAPRS_,PAPRSF_,PCP_,PR_,PDELP_,PNEB_, PQ_,PQCO2_,PQICE_,PQLI_,PQO3_,PT_, &
  ! - INPUT 1D
   & PALB_,PALBDIR_,PEMIS_,PGELAM_, PGEMU_,PMU0_,PMU0LU_,PTS_,PDECRD_,PCLCT_, &
  ! - INPUT/OUTPUT
   & PGDEOSI_,PGUEOSI_,PGMU0_,PGMU0_MIN_,PGMU0_MAX_, PGDEOTI_,PGDEOTI2_,PGUEOTI_,PGUEOTI2_,PGEOLT_,PGEOXT_, &
   & PGRPROX_,PGMIXP_,PGFLUXC_,PGRSURF_,PSDUR_, &
  ! - OUTPUT 2D
   & PFRSO_,PFRTH_, &
  ! - OUTPUT 1D
   & PFRSODS_,PFRSOPS_,PFRSOLU_,PFRTHDS_, &
  ! - INPUT 2D x 6
   & PDAER_)

    TEC = OMP_GET_WTIME ()

#define cpo(x) CALL CPRS (x, x##_, .FALSE.)

cpo (PGDEOSI); cpo (PGUEOSI); cpo (PGMU0); 
cpo (PGMU0_MIN); cpo (PGMU0_MAX); cpo (PGDEOTI); 
cpo (PGDEOTI2); cpo (PGUEOTI); cpo (PGUEOTI2); 
cpo (PGEOLT); cpo (PGEOXT); cpo (PGRPROX);
cpo (PGMIXP); cpo (PGFLUXC); cpo (PGRSURF); 
cpo (PSDUR); cpo (PFRSO); cpo (PFRTH); 
cpo (PFRSODS); cpo (PFRSOPS); cpo (PFRSOLU); 
cpo (PFRTHDS);

#undef cpo

!$acc end data

    TED = OMP_GET_WTIME ()

    ZTC = ZTC + (TEC - TSC)
    ZTD = ZTD + (TED - TSD)

ENDDO

PRINT *, " ZTD = ", ZTD, ZTD / REAL ((KLON*KGPBLK)/KCOUNT, JPRB)
PRINT *, " ZTC = ", ZTC, ZTC / REAL ((KLON*KGPBLK)/KCOUNT, JPRB)

! check output
IF ( LCHECK ) THEN
	CALL CHECK_ACRANEB2(KLON,KLEV, KGPBLK, &
	 & PFRSO,PFRTH, &
	 & PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS)
ENDIF





ZTC = 0.
ZTD = 0.

ts=omp_get_wtime()

DO JCOUNT=1,KCOUNT


    TSD = OMP_GET_WTIME ()

!$acc data &
!$acc   copyin  (YDERDI,YDRIP,YDML_PHY_MF,PAPRS,PAPRSF,PCP,PR,PDELP,PNEB,PQ,PQCO2,PQICE,PQLI,PQO3,PT, &
!$acc            PALB,PALBDIR,PEMIS,PGELAM,PGEMU,PMU0,PMU0LU,PTS,PDECRD,PCLCT,PDAER) &
!$acc   copy    (PGDEOSI,PGUEOSI,PGMU0,PGMU0_MIN,PGMU0_MAX, &
!$acc            PGDEOTI,PGDEOTI2,PGUEOTI,PGUEOTI2,PGEOLT,PGEOXT, &
!$acc            PGRPROX,PGMIXP,PGFLUXC,PGRSURF,PSDUR) &
!$acc   copyout (PFRSO,PFRTH,PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS) 

    TSC = OMP_GET_WTIME ()

  CALL ACRANEB2( &
   & YDERDI,YDRIP,YDML_PHY_MF,KIDIA,KFDIA,KGPBLK,KLON,KTDIA,KLEV,KJN,KSTEP, &
  ! - INPUT 2D
   & PAPRS,PAPRSF,PCP,PR,PDELP,PNEB, PQ,PQCO2,PQICE,PQLI,PQO3,PT, &
  ! - INPUT 1D
   & PALB,PALBDIR,PEMIS,PGELAM, PGEMU,PMU0,PMU0LU,PTS,PDECRD,PCLCT, &
  ! - INPUT/OUTPUT
   & PGDEOSI,PGUEOSI,PGMU0,PGMU0_MIN,PGMU0_MAX, PGDEOTI,PGDEOTI2,PGUEOTI,PGUEOTI2,PGEOLT,PGEOXT, &
   & PGRPROX,PGMIXP,PGFLUXC,PGRSURF,PSDUR, &
  ! - OUTPUT 2D
   & PFRSO,PFRTH, &
  ! - OUTPUT 1D
   & PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS, &
  ! - INPUT 2D x 6
   & PDAER)

    TEC = OMP_GET_WTIME ()

!$acc end data

    TED = OMP_GET_WTIME ()

    ZTC = ZTC + (TEC - TSC)
    ZTD = ZTD + (TED - TSD)

ENDDO

te=omp_get_wtime()
write (*,'(A,F8.2,A)') 'elapsed time : ',te-ts,' s'
write (*,'(A,F8.4,A)') '          i.e. ',1000.*(te-ts)/(KLON*KGPBLK)/KCOUNT,' ms/gp'

PRINT *, " ZTD = ", ZTD, ZTD / REAL ((KLON*KGPBLK)/KCOUNT, JPRB)
PRINT *, " ZTC = ", ZTC, ZTC / REAL ((KLON*KGPBLK)/KCOUNT, JPRB)


! check output
IF ( LCHECK ) THEN
	CALL CHECK_ACRANEB2(KLON,KLEV, KGPBLK, &
	 & PFRSO,PFRTH, &
	 & PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS)
ENDIF

IF (LSAVE) THEN
CALL WR ('PFRSO.dat',   PFRSO)
CALL WR ('PFRTH.dat',   PFRTH)
CALL WR ('PFRSODS.dat', PFRSODS)
CALL WR ('PFRSOPS.dat', PFRSOPS)
CALL WR ('PFRSOLU.dat', PFRSOLU)
CALL WR ('PFRTHDS.dat', PFRTHDS)
ENDIF

END SUBROUTINE WRAPPER

SUBROUTINE CPRS3 (X3, X3_, LDH2D)

REAL (KIND=JPRB) :: X3 (:,:,:,:), X3_ (:,:,:)
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK, I, NI, J, NJ

NLON = SIZE (X3, 1)
NI   = SIZE (X3, 2)
NJ   = SIZE (X3, 3)
NBLK = SIZE (X3, 4)

IF (LDH2D) THEN
!$acc parallel loop present (X3_) copyin (X3) collapse (4)
DO JBLK = 1, NBLK
  DO I = 1, NI
  DO J = 1, NJ
    DO JLON = 1, NLON
      X3_ ((JBLK-1)*NLON+JLON,I,J) = X3 (JLON, I, J, JBLK)
    ENDDO
  ENDDO
  ENDDO
ENDDO
!$acc end parallel loop
ELSE
!$acc parallel loop present (X3_) copyout (X3) collapse (4)
DO JBLK = 1, NBLK
  DO I = 1, NI
  DO J = 1, NJ
    DO JLON = 1, NLON
      X3 (JLON, I, J, JBLK) = X3_ ((JBLK-1)*NLON+JLON,I,J) 
    ENDDO
  ENDDO
  ENDDO
ENDDO
!$acc end parallel loop
ENDIF

END SUBROUTINE

SUBROUTINE CPRS2 (X2, X2_, LDH2D)

REAL (KIND=JPRB) :: X2 (:,:,:), X2_ (:,:)
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK, I, NI

NLON = SIZE (X2, 1)
NI   = SIZE (X2, 2)
NBLK = SIZE (X2, 3)

IF (LDH2D) THEN
!$acc parallel loop present (X2_) copyin (X2) collapse (3)
DO JBLK = 1, NBLK
  DO I = 1, NI
    DO JLON = 1, NLON
      X2_ ((JBLK-1)*NLON+JLON,I) = X2 (JLON, I, JBLK)
    ENDDO
  ENDDO
ENDDO
!$acc end parallel loop
ELSE
!$acc parallel loop present (X2_) copyout (X2) collapse (3)
DO JBLK = 1, NBLK
  DO I = 1, NI
    DO JLON = 1, NLON
      X2 (JLON, I, JBLK) = X2_ ((JBLK-1)*NLON+JLON,I) 
    ENDDO
  ENDDO
ENDDO
!$acc end parallel loop
ENDIF

END SUBROUTINE

SUBROUTINE CPRS1 (X1, X1_, LDH2D)

REAL (KIND=JPRB) :: X1 (:,:), X1_ (:)
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK

NLON = SIZE (X1, 1)
NBLK = SIZE (X1, 2)

IF (LDH2D) THEN
!$acc parallel loop present (X1_) copyin (X1) collapse (2)
DO JBLK = 1, NBLK
  DO JLON = 1, NBLK
    X1_ ((JBLK-1)*NLON+JLON) = X1 (JLON, JBLK)
  ENDDO
ENDDO
!$acc end parallel loop
ELSE
!$acc parallel loop present (X1_) copyout (X1) collapse (2)
DO JBLK = 1, NBLK
  DO JLON = 1, NBLK
    X1 (JLON, JBLK) = X1_ ((JBLK-1)*NLON+JLON) 
  ENDDO
ENDDO
!$acc end parallel loop
ENDIF

END SUBROUTINE

SUBROUTINE WR1 (CDFILE, P1)

CHARACTER (LEN=*) :: CDFILE
REAL(KIND=JPRB)   :: P1 (:)

INTEGER :: J1

OPEN (77, FILE=TRIM (CDFILE), FORM="FORMATTED")

DO J1 = 1, SIZE (P1, 1)
WRITE (77, '(I5,E25.17)') J1, P1 (J1)
ENDDO

CLOSE (77)

END SUBROUTINE

SUBROUTINE WR2 (CDFILE, P2)

CHARACTER (LEN=*) :: CDFILE
REAL(KIND=JPRB)   :: P2 (:,:)

INTEGER :: J1, J2

OPEN (77, FILE=TRIM (CDFILE), FORM="FORMATTED")

DO J1 = 1, SIZE (P2, 1)
DO J2 = 1, SIZE (P2, 2)
WRITE (77, '(I5,I5,E25.17)') J1, J2, P2 (J1, J2)
ENDDO
ENDDO

CLOSE (77)

END SUBROUTINE

SUBROUTINE WR3 (CDFILE, P3)

CHARACTER (LEN=*) :: CDFILE
REAL(KIND=JPRB)   :: P3 (:,:,:)

INTEGER :: J1, J2, J3

OPEN (77, FILE=TRIM (CDFILE), FORM="FORMATTED")

DO J1 = 1, SIZE (P3, 1)
DO J2 = 1, SIZE (P3, 2)
DO J3 = 1, SIZE (P3, 3)
WRITE (77, '(I5,I5,I5,E25.17)') J1, J2, J3, P3 (J1, J2, J3)
ENDDO
ENDDO
ENDDO

CLOSE (77)

END SUBROUTINE

END MODULE WRAPPER_MOD
