INTERFACE

SUBROUTINE ACRANEB2( &
 & KIDIA,KFDIA,KLON,KTDIA,KLEV&
 & )
!$acc routine (ACRANEB2) seq

USE PARKIND1 ,ONLY : JPIM     ,JPRB     ,JPRD

INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN) :: KLON 
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA 
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV 

END SUBROUTINE ACRANEB2

END INTERFACE
