INTERFACE

SUBROUTINE ACRANEB2( &
 & KIDIA,KFDIA,KLON,KTDIA,KLEV&
 & )
!$acc routine (ACRANEB2) seq

INTEGER,INTENT(IN) :: KIDIA 
INTEGER,INTENT(IN) :: KFDIA 
INTEGER,INTENT(IN) :: KLON 
INTEGER,INTENT(IN) :: KTDIA 
INTEGER,INTENT(IN) :: KLEV 

END SUBROUTINE ACRANEB2

END INTERFACE
