PROGRAM MAIN

!$acc serial
CALL ACRANEB2(1,1,32,1,87)
!$acc end serial

CONTAINS

SUBROUTINE ACRANEB2(KIDIA,KFDIA,KLON,KTDIA,KLEV)

!$acc routine (ACRANEB2) seq

IMPLICIT NONE

INTEGER,INTENT(IN) :: KIDIA 
INTEGER,INTENT(IN) :: KFDIA 
INTEGER,INTENT(IN) :: KLON 
INTEGER,INTENT(IN) :: KTDIA 
INTEGER,INTENT(IN) :: KLEV 

INTEGER :: JLEV1, JLEV2

PRINT *, " JLEV1 = ", KTDIA-1, KLEV

DO JLEV1=KTDIA-1,KLEV    
  PRINT *, " JLEV2 = ", JLEV1+1,KLEV
  DO JLEV2=JLEV1+1,KLEV  
    PRINT *, " JLEV2 = ", JLEV2, " JLEV1+1 = ", JLEV1+1, JLEV2 == JLEV1+1
  ENDDO
ENDDO

END SUBROUTINE ACRANEB2
END PROGRAM MAIN
