PROGRAM MAIN

!$acc serial
CALL ACRANEB2(1)
!$acc end serial

CONTAINS

SUBROUTINE ACRANEB2 (KTDIA)

!$acc routine (ACRANEB2) seq

IMPLICIT NONE

INTEGER :: KTDIA 
INTEGER :: JLEV1, JLEV2

DO JLEV1=KTDIA-1,7    
  DO JLEV2=JLEV1+1,7  
    PRINT *, " JLEV2 = ", JLEV2, " JLEV1+1 = ", JLEV1+1, JLEV2 == JLEV1+1
  ENDDO
ENDDO

END SUBROUTINE ACRANEB2
END PROGRAM MAIN
