MODULE LOAD_TERDI_MOD

USE YOERDI, ONLY : TERDI

INTERFACE LOAD
MODULE PROCEDURE LOAD_TERDI
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TERDI (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TERDI), INTENT (OUT) :: YD

READ (KLUN) YD%RRAE
READ (KLUN) YD%RSUNDUR
READ (KLUN) YD%RCARDI
READ (KLUN) YD%RCH4
READ (KLUN) YD%RN2O
READ (KLUN) YD%RNO2
READ (KLUN) YD%RO3
READ (KLUN) YD%RCCL4
READ (KLUN) YD%RCFC11
READ (KLUN) YD%RCFC12
READ (KLUN) YD%RCFC22
READ (KLUN) YD%REPCLC
READ (KLUN) YD%REPH2O
READ (KLUN) YD%RCCO2
READ (KLUN) YD%RCCH4
READ (KLUN) YD%RCN2O
READ (KLUN) YD%RCNO2
READ (KLUN) YD%RCCFC11
READ (KLUN) YD%RCCFC12
READ (KLUN) YD%RCCFC22
READ (KLUN) YD%RCCCL4
READ (KLUN) YD%RSOLINC
END SUBROUTINE


END MODULE
