MODULE LOAD_TPHYDS_MOD

USE YOMPHYDS, ONLY : TPHYDS

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHYDS
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TPHYDS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHYDS), INTENT (OUT) :: YD

READ (KLUN) YD%JPVXP
READ (KLUN) YD%JPVXP2
READ (KLUN) YD%JPCXP
READ (KLUN) YD%JPVEXTR
READ (KLUN) YD%JPVEXTRDI
READ (KLUN) YD%JPVXTR2
READ (KLUN) YD%CEXTRP
READ (KLUN) YD%CXTRP2
READ (KLUN) YD%CVEXTRA
READ (KLUN) YD%CVEXRAD
READ (KLUN) YD%CVEXTRDI
READ (KLUN) YD%CVEXTR2
READ (KLUN) YD%NEXTRPGB
READ (KLUN) YD%NXTRP2GB
READ (KLUN) YD%NVEXTRAGB
READ (KLUN) YD%NVEXRADGB
READ (KLUN) YD%NVEXTR2GB
READ (KLUN) YD%NVEXTRDIGB
READ (KLUN) YD%NSFLUX
READ (KLUN) YD%NSFORC
READ (KLUN) YD%EXTRPDF
READ (KLUN) YD%XTRP2DF
READ (KLUN) YD%VEXTRADF
READ (KLUN) YD%VEXRADDF
READ (KLUN) YD%VEXTR2DF
READ (KLUN) YD%VEXTRDI
READ (KLUN) YD%LREQIN_VEXTRDI
READ (KLUN) YD%LREQOUT_VEXTRDI
END SUBROUTINE


END MODULE
