MODULE LOAD_TVDOZ_MOD

USE YOMVDOZ, ONLY : TVDOZ

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVDOZ
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TVDOZ (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVDOZ), INTENT (OUT) :: YD

READ (KLUN) YD%VDHJS
READ (KLUN) YD%VDHJH
READ (KLUN) YD%VDHNS
READ (KLUN) YD%VDHNH
READ (KLUN) YD%VDPJS
READ (KLUN) YD%VDPJH
READ (KLUN) YD%VDPNS
READ (KLUN) YD%VDPNH
READ (KLUN) YD%VDEJS
READ (KLUN) YD%VDEJH
READ (KLUN) YD%VDENS
READ (KLUN) YD%VDENH
READ (KLUN) YD%VDAJS
READ (KLUN) YD%VDAJH
READ (KLUN) YD%VDANS
READ (KLUN) YD%VDANH
READ (KLUN) YD%VDNJS
READ (KLUN) YD%VDNJH
READ (KLUN) YD%VDNNS
READ (KLUN) YD%VDNNH
READ (KLUN) YD%VOZNJ
READ (KLUN) YD%VOZHS
READ (KLUN) YD%LRDIFOZ
READ (KLUN) YD%LRDEPOZ
END SUBROUTINE


END MODULE
