MODULE LOAD_TTOPH_MOD

USE YOMTOPH, ONLY : TTOPH

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTOPH
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TTOPH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTOPH), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU
READ (KLUN) LRMESOU
IF (LRMESOU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOU (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOU
ENDIF
READ (KLUN) LRMESOT
IF (LRMESOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOT (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOT
ENDIF
READ (KLUN) LRMESOQ
IF (LRMESOQ) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMESOQ (IL1(1):IU1(1)))
  READ (KLUN) YD%RMESOQ
ENDIF
READ (KLUN) YD%RFMESOQ
READ (KLUN) YD%NTQSAT
READ (KLUN) YD%NTDIFU
READ (KLUN) YD%NTCOEF
READ (KLUN) YD%NTDRAG
READ (KLUN) YD%NTCVIM
READ (KLUN) YD%NTPLUI
READ (KLUN) YD%NTRADI
READ (KLUN) YD%NTNEBU
READ (KLUN) YD%NTOZON
READ (KLUN) YD%NTDRME
READ (KLUN) YD%NTCOET
READ (KLUN) YD%NTAJUC
READ (KLUN) YD%NTRELAXT
READ (KLUN) YD%NTRELAXQ
READ (KLUN) YD%NTRELAXU
READ (KLUN) YD%ETQSAT
READ (KLUN) YD%ETDIFU
READ (KLUN) YD%ETCOEF
READ (KLUN) YD%ETDRAG
READ (KLUN) YD%ETCVIM
READ (KLUN) YD%ETPLUI
READ (KLUN) YD%ETRADI
READ (KLUN) YD%ETNEBU
READ (KLUN) YD%ETOZON
READ (KLUN) YD%ETDRME
READ (KLUN) YD%ETCOET
READ (KLUN) YD%ETAJUC
READ (KLUN) YD%ETRELAXT
READ (KLUN) YD%ETRELAXQ
READ (KLUN) YD%ETRELAXU
READ (KLUN) YD%XDRMUK
READ (KLUN) YD%XDRMUX
READ (KLUN) YD%XDRMUP
READ (KLUN) YD%XDRMTK
READ (KLUN) YD%XDRMTX
READ (KLUN) YD%XDRMTP
READ (KLUN) YD%XDRMQK
READ (KLUN) YD%XDRMQP
READ (KLUN) YD%XDRMQX
READ (KLUN) YD%RCLX
READ (KLUN) YD%TPSCLIM
END SUBROUTINE


END MODULE
