MODULE LOAD_TSIMPHL_MOD

USE YOMSIMPHL, ONLY : TSIMPHL

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSIMPHL
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TSIMPHL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSIMPHL), INTENT (OUT) :: YD

READ (KLUN) YD%LSIMPH
READ (KLUN) YD%LTRAJPS
READ (KLUN) YD%LTRAJPST
READ (KLUN) YD%LSMOOTHD
READ (KLUN) YD%LSMOOTHA
READ (KLUN) YD%LSMOOTHB
READ (KLUN) YD%LCVRASP
READ (KLUN) YD%LGWDSP
READ (KLUN) YD%LRAYSP
READ (KLUN) YD%LSTRASP
READ (KLUN) YD%LVDIFSP
READ (KLUN) YD%LVDIFSPNL
READ (KLUN) YD%LRRMESSP
READ (KLUN) YD%LCLOUDS
READ (KLUN) YD%LGWDSPNL
READ (KLUN) YD%LSTRASPN
READ (KLUN) YD%LPROCLDTL
READ (KLUN) YD%LMELTTL
READ (KLUN) YD%LMELTNL
READ (KLUN) YD%LMICROTL
READ (KLUN) YD%LTRAJRAIN
READ (KLUN) YD%LTRAJCOND
READ (KLUN) YD%LNEBCVPPKF
READ (KLUN) YD%LCOLLECTL
READ (KLUN) YD%LEVAPTL
READ (KLUN) YD%LSMOOTHEVP
READ (KLUN) YD%LIGELREPRO
READ (KLUN) YD%LCVRASBM
READ (KLUN) YD%LCONSENTH
READ (KLUN) YD%LAPPROXCONV
READ (KLUN) YD%RHCRIT1S
READ (KLUN) YD%RHCRIT2S
READ (KLUN) YD%TADJ
READ (KLUN) YD%RMINEVP
READ (KLUN) YD%DELTAH
READ (KLUN) YD%RMODULQCPROG
END SUBROUTINE


END MODULE
