MODULE LOAD_TCVMNH_MOD

USE YOMCVMNH, ONLY : TCVMNH

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCVMNH
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TCVMNH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCVMNH), INTENT (OUT) :: YD

READ (KLUN) YD%LDEEP
READ (KLUN) YD%LSHALLOW
READ (KLUN) YD%LDIAGCONV
READ (KLUN) YD%LSETTADJ
READ (KLUN) YD%LREFRESH_ALL
READ (KLUN) YD%LDOWN
READ (KLUN) YD%LSMOOTH
READ (KLUN) YD%OTADJD
READ (KLUN) YD%OTADJS
READ (KLUN) YD%NSETENS
READ (KLUN) YD%NIICE
READ (KLUN) YD%XA25
READ (KLUN) YD%XCRAD
READ (KLUN) YD%XCDEPTH
READ (KLUN) YD%XCDEPTH_D
READ (KLUN) YD%XDTPERT
READ (KLUN) YD%XENTR
READ (KLUN) YD%XZLCL
READ (KLUN) YD%XZPBL
READ (KLUN) YD%XWTRIG
READ (KLUN) YD%XNHGAM
READ (KLUN) YD%XTFRZ1
READ (KLUN) YD%XTFRZ2
READ (KLUN) YD%XSTABT
READ (KLUN) YD%XSTABC
READ (KLUN) YD%XAW
READ (KLUN) YD%XBW
READ (KLUN) YD%XATPERT
READ (KLUN) YD%XBTPERT
END SUBROUTINE


END MODULE
