MODULE LOAD_TPARAR_MOD

USE YOMPARAR, ONLY : TPARAR

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPARAR
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TPARAR (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPARAR), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LXSW_BANDS
READ (KLUN) YD%CMICRO
READ (KLUN) YD%CSEDIM
READ (KLUN) YD%NSPLITR
READ (KLUN) YD%NSPLITG
READ (KLUN) YD%NRR
READ (KLUN) YD%NRRL
READ (KLUN) YD%NRRI
READ (KLUN) YD%NSV
READ (KLUN) YD%NSWB_MNH
READ (KLUN) YD%NGPAR
READ (KLUN) YD%MINPRR
READ (KLUN) YD%MACPRR
READ (KLUN) YD%MINPRS
READ (KLUN) YD%MACPRS
READ (KLUN) YD%MINPRG
READ (KLUN) YD%MACPRG
READ (KLUN) YD%MALBDIR
READ (KLUN) YD%MALBSCA
READ (KLUN) YD%MRAIN
READ (KLUN) YD%MSNOW
READ (KLUN) YD%MGZ0
READ (KLUN) YD%MGZ0H
READ (KLUN) YD%MVQS
READ (KLUN) YD%MVTS
READ (KLUN) YD%MVEMIS
READ (KLUN) YD%MSWDIR
READ (KLUN) YD%MSWDIF
READ (KLUN) YD%MFRTHDS
READ (KLUN) YD%MLSM
READ (KLUN) YD%MCD
READ (KLUN) LXSW_BANDS
IF (LXSW_BANDS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%XSW_BANDS (IL1(1):IU1(1)))
  READ (KLUN) YD%XSW_BANDS
ENDIF
READ (KLUN) YD%LOSUBG_COND
READ (KLUN) YD%LOSEDIC
READ (KLUN) YD%LOWARM
READ (KLUN) YD%LOSIGMAS
READ (KLUN) YD%LOLSMC
READ (KLUN) YD%LOTOWNC
READ (KLUN) YD%LOCND2
READ (KLUN) YD%LGRSN
READ (KLUN) YD%RADGR
READ (KLUN) YD%RADSN
READ (KLUN) YD%VSIGQSAT
READ (KLUN) YD%CMF_UPDRAFT
READ (KLUN) YD%CMF_CLOUD
READ (KLUN) YD%LMIXUV
READ (KLUN) YD%LLCRIT
READ (KLUN) YD%LTOTPREC
READ (KLUN) YD%XALP_PERT
READ (KLUN) YD%XABUO
READ (KLUN) YD%XBENTR
READ (KLUN) YD%XBDETR
READ (KLUN) YD%XCMF
READ (KLUN) YD%XENTR_MF
READ (KLUN) YD%XCRAD_MF
READ (KLUN) YD%XENTR_DRY
READ (KLUN) YD%XDETR_DRY
READ (KLUN) YD%XDETR_LUP
READ (KLUN) YD%XKCF_MF
READ (KLUN) YD%XKRC_MF
READ (KLUN) YD%XTAUSIGMF
READ (KLUN) YD%XPRES_UV
READ (KLUN) YD%XFRAC_UP_MAX
READ (KLUN) YD%XALPHA_MF
READ (KLUN) YD%XSIGMA_MF
READ (KLUN) YD%XA1
READ (KLUN) YD%XB
READ (KLUN) YD%XC
READ (KLUN) YD%XBETA1
READ (KLUN) YD%XR
READ (KLUN) YD%XLAMBDA
READ (KLUN) YD%LTHETAS
READ (KLUN) YD%LSQUALL
READ (KLUN) YD%NREFROI1
READ (KLUN) YD%NREFROI2
READ (KLUN) YD%VSQUALL
READ (KLUN) YD%NPTP
READ (KLUN) YD%NPRINTFR
READ (KLUN) YD%LDIAGWMAX
READ (KLUN) YD%NDIAGWMAX
READ (KLUN) YD%NDTCHEM
READ (KLUN) YD%LAROBU_ENABLE
READ (KLUN) YD%XLINI
READ (KLUN) YD%LHARATU
READ (KLUN) YD%CSUBG_AUCV_RC
READ (KLUN) YD%CSUBG_RC_RR_ACCR
READ (KLUN) YD%CSUBG_RR_EVAP
READ (KLUN) YD%CSUBG_PR_PDF
READ (KLUN) YD%RCRIAUTI
READ (KLUN) YD%RCRIAUTC
READ (KLUN) YD%RT0CRIAUTI
READ (KLUN) YD%LCRIAUTI
READ (KLUN) YD%XTSTEP_TS
READ (KLUN) YD%XMRSTEP
READ (KLUN) YD%NMAXITER_MICRO
READ (KLUN) YD%CSNOWRIMING
READ (KLUN) YD%XFRACM90
READ (KLUN) YD%LNULLWETG
READ (KLUN) YD%LWETGPOST
READ (KLUN) YD%LNULLWETH
READ (KLUN) YD%LWETHPOST
READ (KLUN) YD%LFEEDBACKT
READ (KLUN) YD%LEVLIMIT
READ (KLUN) YD%LCONVHG
READ (KLUN) YD%LCRFLIMIT
READ (KLUN) YD%CFRAC_ICE_ADJUST
READ (KLUN) YD%CFRAC_ICE_SHALLOW_MF
READ (KLUN) YD%LSEDIM_AFTER
READ (KLUN) YD%XSPLIT_MAXCFL
READ (KLUN) YD%LFPREC3D
READ (KLUN) YD%XCQVR
READ (KLUN) YD%GQVPLIM
READ (KLUN) YD%GQVTOP
READ (KLUN) YD%LQVTOP
END SUBROUTINE


END MODULE
