MODULE LOAD_TPHY2_MOD

USE YOMPHY2, ONLY : TPHY2

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY2
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TPHY2 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY2), INTENT (OUT) :: YD

READ (KLUN) YD%NTSHM
READ (KLUN) YD%NTSML
READ (KLUN) YD%TSPHY
READ (KLUN) YD%XMUCVPP
READ (KLUN) YD%XMULAF
READ (KLUN) YD%XDAMP
READ (KLUN) YD%HCLP
READ (KLUN) YD%HTCLS
READ (KLUN) YD%HVCLS
READ (KLUN) YD%HTSHM
READ (KLUN) YD%HTSML
READ (KLUN) YD%HWMOHIGH
READ (KLUN) YD%HWMOLOW
READ (KLUN) YD%GZ0RAF
READ (KLUN) YD%FACRAF
READ (KLUN) YD%HTKERAF
READ (KLUN) YD%LRAFTUR
READ (KLUN) YD%LMULAF
READ (KLUN) YD%LWMOCLOUD
READ (KLUN) YD%LRAFTKE
END SUBROUTINE


END MODULE
