MODULE WRAPPER_MOD

#include "pmstack.h"

CONTAINS

SUBROUTINE WRAPPER(KLON,KLEV,KGPBLK,KCOUNT,LCHECK)

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM     ,JPRB

USE YOMRIP   ,ONLY : TRIP
USE YOERDI   ,ONLY : TERDI

USE PREPARE_ACRANEB2_MOD
USE CHECK_ACRANEB2_MOD

use omp_lib

IMPLICIT NONE

! arguments
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLK
INTEGER(KIND=JPIM), INTENT(IN) :: KCOUNT
LOGICAL, INTENT(IN) :: LCHECK

! acraneb arguments
TYPE(TERDI)        :: YDERDI
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
TYPE(TRIP)         :: YDRIP
INTEGER(KIND=JPIM) :: KIDIA 
INTEGER(KIND=JPIM) :: KFDIA 
INTEGER(KIND=JPIM) :: KTDIA 
INTEGER(KIND=JPIM) :: KJN
INTEGER(KIND=JPIM) :: KSTEP
REAL(KIND=JPRB) :: PAPRS(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PAPRSF(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PCP(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PR(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PDELP(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PNEB(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQ(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQCO2(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQICE(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQLI(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PQO3(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PT(KLON,KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PALB(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PALBDIR(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PEMIS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PGELAM(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PGEMU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PMU0(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PMU0LU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PTS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PDECRD(KLON,KGPBLK)
REAL(KIND=JPRB) :: PCLCT(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGDEOSI(KLON,0:KLEV,2,KGPBLK)
REAL(KIND=JPRB) :: PGUEOSI(KLON,0:KLEV,2,KGPBLK)
REAL(KIND=JPRB) :: PGMU0(KLON,0:0,KGPBLK)
REAL(KIND=JPRB) :: PGMU0_MIN(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGMU0_MAX(KLON,KGPBLK)
REAL(KIND=JPRB) :: PGDEOTI(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGDEOTI2(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGUEOTI(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGUEOTI2(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGEOLT(KLON,KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGEOXT(KLON,KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGRPROX(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGMIXP(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGFLUXC(KLON,0:KLEV,KGPBLK)
REAL(KIND=JPRB) :: PGRSURF(KLON,KGPBLK)
REAL(KIND=JPRB) :: PSDUR(KLON,KGPBLK)
REAL(KIND=JPRB) :: PFRSO(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PFRTH(KLON,0:KLEV,KGPBLK) 
REAL(KIND=JPRB) :: PFRSODS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRSOPS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRSOLU(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PFRTHDS(KLON,KGPBLK) 
REAL(KIND=JPRB) :: PDAER(KLON,KLEV,6,KGPBLK) 

! stack stuff
INTEGER(KIND=8)          :: NSTACKSIZE
INTEGER(KIND=8)          :: KSTACKPTR
REAL(KIND=JPRB), POINTER ::  PSTACK(:,:)

real(kind=8) :: ts,te

INTEGER :: JCOUNT, JBLK, JLON

! allocate stack
NSTACKSIZE=51000*KLON
KSTACKPTR=1
ALLOCATE(PSTACK(NSTACKSIZE,KGPBLK))


CALL PREPARE_ACRANEB2(YDERDI,YDRIP,YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,KJN,KSTEP, &
 & KGPBLK, &
 & PAPRS,PAPRSF,PCP,PR,PDELP,PNEB,PQ,PQCO2,PQICE,PQLI,PQO3,PT, &
 & PALB,PALBDIR,PEMIS,PGELAM,PGEMU,PMU0,PMU0LU,PTS,PDECRD,PCLCT, &
 & PGDEOSI,PGUEOSI,PGMU0,PGMU0_MIN,PGMU0_MAX, &
 & PGDEOTI,PGDEOTI2,PGUEOTI,PGUEOTI2,PGEOLT,PGEOXT, &
 & PGRPROX,PGMIXP,PGFLUXC,PGRSURF,PSDUR, &
 & PFRSO,PFRTH, &
 & PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS, &
 & PDAER)

ts=omp_get_wtime()

DO JCOUNT=1,KCOUNT

  !$acc data &
	!$acc&   copyin( YDERDI,YDRIP,YDML_PHY_MF, &
  !$acc&     PAPRS,PAPRSF,PCP,PR,PDELP,PNEB,PQ,PQCO2,PQICE,PQLI,PQO3,PT, &
  !$acc&     PALB,PALBDIR,PEMIS,PGELAM,PGEMU,PMU0,PMU0LU,PTS,PDECRD,PCLCT, &
  !$acc&     PDAER) &
	!$acc&   create(PSTACK) &
  !$acc&   copy(PGDEOSI,PGUEOSI,PGMU0,PGMU0_MIN,PGMU0_MAX, &
  !$acc&     PGDEOTI,PGDEOTI2,PGUEOTI,PGUEOTI2,PGEOLT,PGEOXT, &
  !$acc&     PGRPROX,PGMIXP,PGFLUXC,PGRSURF,PSDUR) &
  !$acc&   copyout(PFRSO,PFRTH, &
  !$acc&     PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS)

	DO JBLK=1,KGPBLK
			
			CALL ACRANEB2( &
			 & YDERDI,YDRIP,YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,KJN,KSTEP, &
			! - INPUT 2D
			 & PAPRS(:,:,JBLK),PAPRSF(:,:,JBLK),PCP(:,:,JBLK),PR(:,:,JBLK),PDELP(:,:,JBLK),PNEB(:,:,JBLK), &
			 & PQ(:,:,JBLK),PQCO2(:,:,JBLK),PQICE(:,:,JBLK),PQLI(:,:,JBLK),PQO3(:,:,JBLK),PT(:,:,JBLK), &
			! - INPUT 1D
			 & PALB(:,JBLK),PALBDIR(:,JBLK),PEMIS(:,JBLK),PGELAM(:,JBLK), &
			 & PGEMU(:,JBLK),PMU0(:,JBLK),PMU0LU(:,JBLK),PTS(:,JBLK),PDECRD(:,JBLK),PCLCT(:,JBLK), &
			! - INPUT/OUTPUT
			 & PGDEOSI(:,:,:,JBLK),PGUEOSI(:,:,:,JBLK),PGMU0(:,:,JBLK),PGMU0_MIN(:,JBLK),PGMU0_MAX(:,JBLK), &
			 & PGDEOTI(:,:,JBLK),PGDEOTI2(:,:,JBLK),PGUEOTI(:,:,JBLK),PGUEOTI2(:,:,JBLK),PGEOLT(:,:,JBLK),PGEOXT(:,:,JBLK), &
			 & PGRPROX(:,:,JBLK),PGMIXP(:,:,JBLK),PGFLUXC(:,:,JBLK),PGRSURF(:,JBLK),PSDUR(:,JBLK), &
			! - OUTPUT 2D
			 & PFRSO(:,:,JBLK),PFRTH(:,:,JBLK), &
			! - OUTPUT 1D
			 & PFRSODS(:,JBLK),PFRSOPS(:,JBLK),PFRSOLU(:,JBLK),PFRTHDS(:,JBLK), &
			! - INPUT 2D x 6
			 & PDAER(:,:,:,JBLK), &
			 & NSTACKSIZE,KSTACKPTR,PSTACK(:,JBLK) )

	ENDDO

  !$acc end data

ENDDO

te=omp_get_wtime()
write (*,'(A,F8.2,A)') 'elapsed time : ',te-ts,' s'
write (*,'(A,F8.4,A)') '          i.e. ',1000.*(te-ts)/(KLON*KGPBLK)/KCOUNT,' ms/gp'

! check output
IF ( LCHECK ) THEN
	CALL CHECK_ACRANEB2(KLON,KLEV, KGPBLK, &
	 & PFRSO,PFRTH, &
	 & PFRSODS,PFRSOPS,PFRSOLU,PFRTHDS)
ENDIF

END SUBROUTINE WRAPPER

END MODULE WRAPPER_MOD
